// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides storage functions using Ent as the backend.
// The functions maintain the same interface as file storage for compatibility.

package storage

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/openchami/fabrica/pkg/reconcile"
	fabricaStorage "github.com/openchami/fabrica/pkg/storage"

	"github.com/OpenCHAMI/inventory-service/internal/storage/ent"
	entresource "github.com/OpenCHAMI/inventory-service/internal/storage/ent/resource"

	v1 "github.com/OpenCHAMI/inventory-service/apis/inventory-service.openchami.org/v1"
)

// ErrNotFound indicates that a resource was not found
var ErrNotFound = errors.New("resource not found")

// Ent client (initialized in main.go)
var entClient *ent.Client

// SetEntClient sets the Ent client for storage operations
func SetEntClient(client *ent.Client) {
	entClient = client
}

// LoadAllComponents loads all Component resources from Ent storage
func LoadAllComponents(ctx context.Context) ([]*v1.Component, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("Component")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load Component resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.Component
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.Component))
	}

	return resources, nil
}

// LoadComponent loads a single Component resource by UID from Ent storage
func LoadComponent(ctx context.Context, uid string) (*v1.Component, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("Component"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load Component %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.Component), nil
}

// SaveComponent saves a Component resource to Ent storage
func SaveComponent(ctx context.Context, resource *v1.Component) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert Component to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check Component existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create Component: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update Component: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteComponent deletes a Component resource from Ent storage
func DeleteComponent(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("Component"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete Component %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllComponentEndpoints loads all ComponentEndpoint resources from Ent storage
func LoadAllComponentEndpoints(ctx context.Context) ([]*v1.ComponentEndpoint, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("ComponentEndpoint")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load ComponentEndpoint resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.ComponentEndpoint
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.ComponentEndpoint))
	}

	return resources, nil
}

// LoadComponentEndpoint loads a single ComponentEndpoint resource by UID from Ent storage
func LoadComponentEndpoint(ctx context.Context, uid string) (*v1.ComponentEndpoint, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("ComponentEndpoint"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load ComponentEndpoint %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.ComponentEndpoint), nil
}

// SaveComponentEndpoint saves a ComponentEndpoint resource to Ent storage
func SaveComponentEndpoint(ctx context.Context, resource *v1.ComponentEndpoint) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert ComponentEndpoint to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check ComponentEndpoint existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create ComponentEndpoint: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update ComponentEndpoint: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteComponentEndpoint deletes a ComponentEndpoint resource from Ent storage
func DeleteComponentEndpoint(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("ComponentEndpoint"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete ComponentEndpoint %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllEthernetInterfaces loads all EthernetInterface resources from Ent storage
func LoadAllEthernetInterfaces(ctx context.Context) ([]*v1.EthernetInterface, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("EthernetInterface")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load EthernetInterface resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.EthernetInterface
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.EthernetInterface))
	}

	return resources, nil
}

// LoadEthernetInterface loads a single EthernetInterface resource by UID from Ent storage
func LoadEthernetInterface(ctx context.Context, uid string) (*v1.EthernetInterface, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("EthernetInterface"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load EthernetInterface %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.EthernetInterface), nil
}

// SaveEthernetInterface saves a EthernetInterface resource to Ent storage
func SaveEthernetInterface(ctx context.Context, resource *v1.EthernetInterface) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert EthernetInterface to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check EthernetInterface existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create EthernetInterface: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update EthernetInterface: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteEthernetInterface deletes a EthernetInterface resource from Ent storage
func DeleteEthernetInterface(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("EthernetInterface"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete EthernetInterface %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllGroups loads all Group resources from Ent storage
func LoadAllGroups(ctx context.Context) ([]*v1.Group, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("Group")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load Group resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.Group
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.Group))
	}

	return resources, nil
}

// LoadGroup loads a single Group resource by UID from Ent storage
func LoadGroup(ctx context.Context, uid string) (*v1.Group, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("Group"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load Group %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.Group), nil
}

// SaveGroup saves a Group resource to Ent storage
func SaveGroup(ctx context.Context, resource *v1.Group) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert Group to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check Group existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create Group: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update Group: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteGroup deletes a Group resource from Ent storage
func DeleteGroup(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("Group"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete Group %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllHardwares loads all Hardware resources from Ent storage
func LoadAllHardwares(ctx context.Context) ([]*v1.Hardware, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("Hardware")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load Hardware resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.Hardware
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.Hardware))
	}

	return resources, nil
}

// LoadHardware loads a single Hardware resource by UID from Ent storage
func LoadHardware(ctx context.Context, uid string) (*v1.Hardware, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("Hardware"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load Hardware %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.Hardware), nil
}

// SaveHardware saves a Hardware resource to Ent storage
func SaveHardware(ctx context.Context, resource *v1.Hardware) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Derive resource_id from Spec.ID (xname), matching the pattern used by other resource types
	resource.ID = resource.Spec.ID

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert Hardware to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check Hardware existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create Hardware: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update Hardware: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteHardware deletes a Hardware resource from Ent storage
func DeleteHardware(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("Hardware"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete Hardware %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllRedfishEndpoints loads all RedfishEndpoint resources from Ent storage
func LoadAllRedfishEndpoints(ctx context.Context) ([]*v1.RedfishEndpoint, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("RedfishEndpoint")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load RedfishEndpoint resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.RedfishEndpoint
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.RedfishEndpoint))
	}

	return resources, nil
}

// LoadRedfishEndpoint loads a single RedfishEndpoint resource by UID from Ent storage
func LoadRedfishEndpoint(ctx context.Context, uid string) (*v1.RedfishEndpoint, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("RedfishEndpoint"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load RedfishEndpoint %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.RedfishEndpoint), nil
}

// SaveRedfishEndpoint saves a RedfishEndpoint resource to Ent storage
func SaveRedfishEndpoint(ctx context.Context, resource *v1.RedfishEndpoint) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert RedfishEndpoint to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check RedfishEndpoint existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create RedfishEndpoint: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update RedfishEndpoint: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteRedfishEndpoint deletes a RedfishEndpoint resource from Ent storage
func DeleteRedfishEndpoint(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("RedfishEndpoint"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete RedfishEndpoint %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

// LoadAllServiceEndpoints loads all ServiceEndpoint resources from Ent storage
func LoadAllServiceEndpoints(ctx context.Context) ([]*v1.ServiceEndpoint, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query all resources of this kind
	entResources, err := entClient.Resource.Query().
		Where(entresource.KindEQ("ServiceEndpoint")).
		WithLabels().
		WithAnnotations().
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to load ServiceEndpoint resources: %w", err)
	}

	// Convert to Fabrica resources
	var resources []*v1.ServiceEndpoint
	for _, entResource := range entResources {
		fabricaResource, err := FromEntResource(ctx, entResource)
		if err != nil {
			// Log error but continue with other resources
			continue
		}
		resources = append(resources, fabricaResource.(*v1.ServiceEndpoint))
	}

	return resources, nil
}

// LoadServiceEndpoint loads a single ServiceEndpoint resource by UID from Ent storage
func LoadServiceEndpoint(ctx context.Context, uid string) (*v1.ServiceEndpoint, error) {
	if entClient == nil {
		return nil, fmt.Errorf("ent client not initialized")
	}

	// Query by UID and kind
	entResource, err := entClient.Resource.Query().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("ServiceEndpoint"),
		).
		WithLabels().
		WithAnnotations().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("failed to load ServiceEndpoint %s: %w", uid, err)
	}

	// Convert to Fabrica resource
	fabricaResource, err := FromEntResource(ctx, entResource)
	if err != nil {
		return nil, err
	}

	return fabricaResource.(*v1.ServiceEndpoint), nil
}

// SaveServiceEndpoint saves a ServiceEndpoint resource to Ent storage
func SaveServiceEndpoint(ctx context.Context, resource *v1.ServiceEndpoint) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Convert to Ent entity
	createBuilder, labels, annotations, err := ToEntResource(resource)
	if err != nil {
		return fmt.Errorf("failed to convert ServiceEndpoint to ent: %w", err)
	}

	// Use upsert pattern: try to update, if not exists then create
	entResource, err := entClient.Resource.Query().
		Where(entresource.UIDEQ(resource.GetUID())).
		Only(ctx)

	if err != nil && !ent.IsNotFound(err) {
		return fmt.Errorf("failed to check ServiceEndpoint existence: %w", err)
	}

	var savedResource *ent.Resource
	if ent.IsNotFound(err) {
		// Create new resource
		savedResource, err = createBuilder.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to create ServiceEndpoint: %w", err)
		}
	} else {
		// Update existing resource
		spec, _ := json.Marshal(resource.Spec)
		status, _ := json.Marshal(resource.Status)

		updateOp := entClient.Resource.UpdateOne(entResource).
			SetName(resource.Metadata.Name).
			SetAPIVersion(resource.APIVersion).
			SetSpec(spec).
			SetStatus(status).
			SetUpdatedAt(time.Now())

		if resource.ID != "" {
			updateOp = updateOp.SetResourceID(resource.ID)
		} else {
			updateOp = updateOp.ClearResourceID()
		}

		savedResource, err = updateOp.Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to update ServiceEndpoint: %w", err)
		}
	}

	// Save labels
	if err := saveLabels(ctx, savedResource.ID, labels); err != nil {
		return err
	}

	// Save annotations
	if err := saveAnnotations(ctx, savedResource.ID, annotations); err != nil {
		return err
	}

	return nil
}

// DeleteServiceEndpoint deletes a ServiceEndpoint resource from Ent storage
func DeleteServiceEndpoint(ctx context.Context, uid string) error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}

	// Delete by UID
	deleted, err := entClient.Resource.Delete().
		Where(
			entresource.UIDEQ(uid),
			entresource.KindEQ("ServiceEndpoint"),
		).
		Exec(ctx)

	if err != nil {
		return fmt.Errorf("failed to delete ServiceEndpoint %s: %w", uid, err)
	}

	if deleted == 0 {
		return ErrNotFound
	}

	return nil
}

var Backend fabricaStorage.StorageBackend = &entStorageBackend{}

var _ fabricaStorage.StorageBackend = (*entStorageBackend)(nil)

type entStorageBackend struct{}

func ensureBackendReady() error {
	if entClient == nil {
		return fmt.Errorf("ent client not initialized")
	}
	return nil
}

func (b *entStorageBackend) LoadAll(ctx context.Context, resourceType string) ([]json.RawMessage, error) {
	if err := ensureBackendReady(); err != nil {
		return nil, err
	}
	switch resourceType {
	case "Component":
		resources, err := LoadAllComponents(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "ComponentEndpoint":
		resources, err := LoadAllComponentEndpoints(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "EthernetInterface":
		resources, err := LoadAllEthernetInterfaces(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "Group":
		resources, err := LoadAllGroups(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "Hardware":
		resources, err := LoadAllHardwares(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "RedfishEndpoint":
		resources, err := LoadAllRedfishEndpoints(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	case "ServiceEndpoint":
		resources, err := LoadAllServiceEndpoints(ctx)
		if err != nil {
			return nil, err
		}
		return marshalTypedList(resources)
	default:
		return nil, fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Load(ctx context.Context, resourceType, uid string) (json.RawMessage, error) {
	if err := ensureBackendReady(); err != nil {
		return nil, err
	}
	switch resourceType {
	case "Component":
		resource, err := LoadComponent(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "ComponentEndpoint":
		resource, err := LoadComponentEndpoint(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "EthernetInterface":
		resource, err := LoadEthernetInterface(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "Group":
		resource, err := LoadGroup(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "Hardware":
		resource, err := LoadHardware(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "RedfishEndpoint":
		resource, err := LoadRedfishEndpoint(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	case "ServiceEndpoint":
		resource, err := LoadServiceEndpoint(ctx, uid)
		if err != nil {
			return nil, err
		}
		return marshalResource(resource)
	default:
		return nil, fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Save(ctx context.Context, resourceType, uid string, data json.RawMessage) error {
	if err := ensureBackendReady(); err != nil {
		return err
	}
	switch resourceType {
	case "Component":
		var res v1.Component
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal Component: %w", err)
		}
		res.Metadata.UID = uid
		return SaveComponent(ctx, &res)
	case "ComponentEndpoint":
		var res v1.ComponentEndpoint
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal ComponentEndpoint: %w", err)
		}
		res.Metadata.UID = uid
		return SaveComponentEndpoint(ctx, &res)
	case "EthernetInterface":
		var res v1.EthernetInterface
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal EthernetInterface: %w", err)
		}
		res.Metadata.UID = uid
		return SaveEthernetInterface(ctx, &res)
	case "Group":
		var res v1.Group
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal Group: %w", err)
		}
		res.Metadata.UID = uid
		return SaveGroup(ctx, &res)
	case "Hardware":
		var res v1.Hardware
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal Hardware: %w", err)
		}
		res.Metadata.UID = uid
		return SaveHardware(ctx, &res)
	case "RedfishEndpoint":
		var res v1.RedfishEndpoint
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal RedfishEndpoint: %w", err)
		}
		res.Metadata.UID = uid
		return SaveRedfishEndpoint(ctx, &res)
	case "ServiceEndpoint":
		var res v1.ServiceEndpoint
		if err := json.Unmarshal(data, &res); err != nil {
			return fmt.Errorf("failed to unmarshal ServiceEndpoint: %w", err)
		}
		res.Metadata.UID = uid
		return SaveServiceEndpoint(ctx, &res)
	default:
		return fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Delete(ctx context.Context, resourceType, uid string) error {
	if err := ensureBackendReady(); err != nil {
		return err
	}
	switch resourceType {
	case "Component":
		return DeleteComponent(ctx, uid)
	case "ComponentEndpoint":
		return DeleteComponentEndpoint(ctx, uid)
	case "EthernetInterface":
		return DeleteEthernetInterface(ctx, uid)
	case "Group":
		return DeleteGroup(ctx, uid)
	case "Hardware":
		return DeleteHardware(ctx, uid)
	case "RedfishEndpoint":
		return DeleteRedfishEndpoint(ctx, uid)
	case "ServiceEndpoint":
		return DeleteServiceEndpoint(ctx, uid)
	default:
		return fmt.Errorf("storage: unsupported resource type %s", resourceType)
	}
}

func (b *entStorageBackend) Exists(ctx context.Context, resourceType, uid string) (bool, error) {
	_, err := b.Load(ctx, resourceType, uid)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

func (b *entStorageBackend) List(ctx context.Context, resourceType string) ([]string, error) {
	items, err := b.LoadAll(ctx, resourceType)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, item := range items {
		uid, err := extractUID(item)
		if err != nil {
			return nil, err
		}
		out = append(out, uid)
	}
	return out, nil
}

func (b *entStorageBackend) LoadWithVersion(ctx context.Context, resourceType, uid, version string) (json.RawMessage, string, error) {
	data, err := b.Load(ctx, resourceType, uid)
	if err != nil {
		return nil, "", err
	}
	if version == "" {
		version = ""
	}
	return data, version, nil
}

func (b *entStorageBackend) LoadAllWithVersion(ctx context.Context, resourceType, version string) ([]json.RawMessage, error) {
	return b.LoadAll(ctx, resourceType)
}

func (b *entStorageBackend) SaveWithVersion(ctx context.Context, resourceType, uid string, data json.RawMessage, version string) error {
	return b.Save(ctx, resourceType, uid, data)
}

func (b *entStorageBackend) Close() error {
	return nil
}

type StorageClient struct {
	backend fabricaStorage.StorageBackend
}

var _ reconcile.ClientInterface = (*StorageClient)(nil)

func NewStorageClient() *StorageClient {
	if err := ensureBackendReady(); err != nil {
		panic(err)
	}
	return &StorageClient{backend: Backend}
}

func (c *StorageClient) Get(ctx context.Context, kind, uid string) (interface{}, error) {
	raw, err := c.backend.Load(ctx, kind, uid)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "Component":
		var resource v1.Component
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Component: %w", err)
		}
		return &resource, nil
	case "ComponentEndpoint":
		var resource v1.ComponentEndpoint
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal ComponentEndpoint: %w", err)
		}
		return &resource, nil
	case "EthernetInterface":
		var resource v1.EthernetInterface
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal EthernetInterface: %w", err)
		}
		return &resource, nil
	case "Group":
		var resource v1.Group
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Group: %w", err)
		}
		return &resource, nil
	case "Hardware":
		var resource v1.Hardware
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Hardware: %w", err)
		}
		return &resource, nil
	case "RedfishEndpoint":
		var resource v1.RedfishEndpoint
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal RedfishEndpoint: %w", err)
		}
		return &resource, nil
	case "ServiceEndpoint":
		var resource v1.ServiceEndpoint
		if err := json.Unmarshal(raw, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal ServiceEndpoint: %w", err)
		}
		return &resource, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

func (c *StorageClient) List(ctx context.Context, kind string) ([]interface{}, error) {
	items, err := c.backend.LoadAll(ctx, kind)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "Component":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.Component
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal Component: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "ComponentEndpoint":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.ComponentEndpoint
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal ComponentEndpoint: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "EthernetInterface":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.EthernetInterface
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal EthernetInterface: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "Group":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.Group
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal Group: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "Hardware":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.Hardware
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal Hardware: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "RedfishEndpoint":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.RedfishEndpoint
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal RedfishEndpoint: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "ServiceEndpoint":
		result := make([]interface{}, 0, len(items))
		for _, item := range items {
			var resource v1.ServiceEndpoint
			if err := json.Unmarshal(item, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal ServiceEndpoint: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

func (c *StorageClient) Update(ctx context.Context, resource interface{}) error {
	data, err := json.Marshal(resource)
	if err != nil {
		return fmt.Errorf("failed to marshal resource: %w", err)
	}

	// Extract kind and UID based on type
	switch res := resource.(type) {
	case *v1.Component:
		return c.backend.Save(ctx, "Component", res.Metadata.UID, data)
	case *v1.ComponentEndpoint:
		return c.backend.Save(ctx, "ComponentEndpoint", res.Metadata.UID, data)
	case *v1.EthernetInterface:
		return c.backend.Save(ctx, "EthernetInterface", res.Metadata.UID, data)
	case *v1.Group:
		return c.backend.Save(ctx, "Group", res.Metadata.UID, data)
	case *v1.RedfishEndpoint:
		return c.backend.Save(ctx, "RedfishEndpoint", res.Metadata.UID, data)
	case *v1.ServiceEndpoint:
		return c.backend.Save(ctx, "ServiceEndpoint", res.Metadata.UID, data)
	default:
		return fmt.Errorf("unsupported resource type: %T", resource)
	}
}

func (c *StorageClient) Create(ctx context.Context, resource interface{}) error {
	return c.Update(ctx, resource)
}

func (c *StorageClient) Delete(ctx context.Context, kind, uid string) error {
	return c.backend.Delete(ctx, kind, uid)
}

func marshalTypedList[T any](items []*T) ([]json.RawMessage, error) {
	var out []json.RawMessage
	for _, item := range items {
		data, err := json.Marshal(item)
		if err != nil {
			return nil, err
		}
		out = append(out, json.RawMessage(data))
	}
	return out, nil
}

func marshalResource(resource interface{}) (json.RawMessage, error) {
	data, err := json.Marshal(resource)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(data), nil
}

func extractUID(raw json.RawMessage) (string, error) {
	var wrapper struct {
		Metadata struct {
			UID string `json:"uid"`
		} `json:"metadata"`
	}
	if err := json.Unmarshal(raw, &wrapper); err != nil {
		return "", err
	}
	return wrapper.Metadata.UID, nil
}
