// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/OpenCHAMI/inventory-service/apis/inventory-service.openchami.org/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.Component{}); err != nil {
		return fmt.Errorf("failed to register Component: %w", err)
	}
	if err := gen.RegisterResource(&v1.ComponentEndpoint{}); err != nil {
		return fmt.Errorf("failed to register ComponentEndpoint: %w", err)
	}
	if err := gen.RegisterResource(&v1.EthernetInterface{}); err != nil {
		return fmt.Errorf("failed to register EthernetInterface: %w", err)
	}
	if err := gen.RegisterResource(&v1.Group{}); err != nil {
		return fmt.Errorf("failed to register Group: %w", err)
	}
	if err := gen.RegisterResource(&v1.Hardware{}); err != nil {
		return fmt.Errorf("failed to register Hardware: %w", err)
	}
	if err := gen.RegisterResource(&v1.RedfishEndpoint{}); err != nil {
		return fmt.Errorf("failed to register RedfishEndpoint: %w", err)
	}
	if err := gen.RegisterResource(&v1.ServiceEndpoint{}); err != nil {
		return fmt.Errorf("failed to register ServiceEndpoint: %w", err)
	}

	return nil
}
