// Code generated by fabrica codegen init. DO NOT EDIT.
package resources

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/openchami/fabrica/pkg/codegen"
	"github.com/user/smd2/pkg/resources/component"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica codegen init' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&component.Component{}); err != nil {
		return fmt.Errorf("failed to register Component: %w", err)
	}
	// Set per-resource tags based on source markers
	if hasVersioningMarker("Component") {
		gen.SetResourceTag("Component", "versioning", "enabled")
	}

	return nil
}

// hasVersioningMarker inspects the resource source file for the versioning marker comment.
func hasVersioningMarker(resourceName string) bool {
	// Derive path: pkg/resources/<lower(resourceName)>/<lower(resourceName)>.go
	pkg := strings.ToLower(resourceName)
	path := filepath.Join("pkg", "resources", pkg, pkg+".go")
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	content := string(data)
	return strings.Contains(content, "+fabrica:resource-versioning=enabled")
}
