// Code generated by Fabrica v0.4.0-7-gc8d4f50. DO NOT EDIT.
// Template: apiversion/register.gotmpl
// Generated at: 2026-04-22T11:55:49-06:00

package apiversion

import (
	"github.com/openchami/fabrica/pkg/apiversion"
	"github.com/openchami/fabrica/pkg/versioning"
)

// Registry is the global API version registry
var Registry *apiversion.Registry

func init() {
	Registry = apiversion.NewRegistry()
	Registry.RegisterGroup(apiversion.Group{
		Name:           "inventory-service.openchami.org",
		StorageVersion: "v1",
		Spokes:         []string{"v1"},
	})
	if err := versioning.GlobalVersionRegistry.RegisterVersion("Component", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("RedfishEndpoint", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("ComponentEndpoint", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("EthernetInterface", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("ServiceEndpoint", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("Group", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("Hardware", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
}

// GetRegistry returns the global version registry
func GetRegistry() *apiversion.Registry {
	return Registry
}
