// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/annotation"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/predicate"
)

// AnnotationDelete is the builder for deleting a Annotation entity.
type AnnotationDelete struct {
	config
	hooks    []Hook
	mutation *AnnotationMutation
}

// Where appends a list predicates to the AnnotationDelete builder.
func (_d *AnnotationDelete) Where(ps ...predicate.Annotation) *AnnotationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnnotationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnotationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnnotationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(annotation.Table, sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnnotationDeleteOne is the builder for deleting a single Annotation entity.
type AnnotationDeleteOne struct {
	_d *AnnotationDelete
}

// Where appends a list predicates to the AnnotationDelete builder.
func (_d *AnnotationDeleteOne) Where(ps ...predicate.Annotation) *AnnotationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnnotationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{annotation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnotationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
