// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/label"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/predicate"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/resource"
)

// LabelUpdate is the builder for updating Label entities.
type LabelUpdate struct {
	config
	hooks    []Hook
	mutation *LabelMutation
}

// Where appends a list predicates to the LabelUpdate builder.
func (_u *LabelUpdate) Where(ps ...predicate.Label) *LabelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *LabelUpdate) SetKey(v string) *LabelUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *LabelUpdate) SetNillableKey(v *string) *LabelUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *LabelUpdate) SetValue(v string) *LabelUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *LabelUpdate) SetNillableValue(v *string) *LabelUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetResourceID sets the "resource" edge to the Resource entity by ID.
func (_u *LabelUpdate) SetResourceID(id int) *LabelUpdate {
	_u.mutation.SetResourceID(id)
	return _u
}

// SetResource sets the "resource" edge to the Resource entity.
func (_u *LabelUpdate) SetResource(v *Resource) *LabelUpdate {
	return _u.SetResourceID(v.ID)
}

// Mutation returns the LabelMutation object of the builder.
func (_u *LabelUpdate) Mutation() *LabelMutation {
	return _u.mutation
}

// ClearResource clears the "resource" edge to the Resource entity.
func (_u *LabelUpdate) ClearResource() *LabelUpdate {
	_u.mutation.ClearResource()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LabelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LabelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LabelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LabelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LabelUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := label.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Label.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := label.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Label.value": %w`, err)}
		}
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Label.resource"`)
	}
	return nil
}

func (_u *LabelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(label.Table, label.Columns, sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(label.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(label.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{label.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LabelUpdateOne is the builder for updating a single Label entity.
type LabelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LabelMutation
}

// SetKey sets the "key" field.
func (_u *LabelUpdateOne) SetKey(v string) *LabelUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *LabelUpdateOne) SetNillableKey(v *string) *LabelUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *LabelUpdateOne) SetValue(v string) *LabelUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *LabelUpdateOne) SetNillableValue(v *string) *LabelUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetResourceID sets the "resource" edge to the Resource entity by ID.
func (_u *LabelUpdateOne) SetResourceID(id int) *LabelUpdateOne {
	_u.mutation.SetResourceID(id)
	return _u
}

// SetResource sets the "resource" edge to the Resource entity.
func (_u *LabelUpdateOne) SetResource(v *Resource) *LabelUpdateOne {
	return _u.SetResourceID(v.ID)
}

// Mutation returns the LabelMutation object of the builder.
func (_u *LabelUpdateOne) Mutation() *LabelMutation {
	return _u.mutation
}

// ClearResource clears the "resource" edge to the Resource entity.
func (_u *LabelUpdateOne) ClearResource() *LabelUpdateOne {
	_u.mutation.ClearResource()
	return _u
}

// Where appends a list predicates to the LabelUpdate builder.
func (_u *LabelUpdateOne) Where(ps ...predicate.Label) *LabelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LabelUpdateOne) Select(field string, fields ...string) *LabelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Label entity.
func (_u *LabelUpdateOne) Save(ctx context.Context) (*Label, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LabelUpdateOne) SaveX(ctx context.Context) *Label {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LabelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LabelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LabelUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := label.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Label.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := label.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Label.value": %w`, err)}
		}
	}
	if _u.mutation.ResourceCleared() && len(_u.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Label.resource"`)
	}
	return nil
}

func (_u *LabelUpdateOne) sqlSave(ctx context.Context) (_node *Label, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(label.Table, label.Columns, sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Label.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, label.FieldID)
		for _, f := range fields {
			if !label.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != label.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(label.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(label.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Label{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{label.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
