// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/annotation"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/label"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/predicate"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/resource"
)

// ResourceUpdate is the builder for updating Resource entities.
type ResourceUpdate struct {
	config
	hooks    []Hook
	mutation *ResourceMutation
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdate) Where(ps ...predicate.Resource) *ResourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ResourceUpdate) SetName(v string) *ResourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableName(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *ResourceUpdate) SetAPIVersion(v string) *ResourceUpdate {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableAPIVersion(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ResourceUpdate) SetKind(v string) *ResourceUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableKind(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ResourceUpdate) SetResourceType(v string) *ResourceUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableResourceType(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetSpec sets the "spec" field.
func (_u *ResourceUpdate) SetSpec(v json.RawMessage) *ResourceUpdate {
	_u.mutation.SetSpec(v)
	return _u
}

// AppendSpec appends value to the "spec" field.
func (_u *ResourceUpdate) AppendSpec(v json.RawMessage) *ResourceUpdate {
	_u.mutation.AppendSpec(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdate) SetStatus(v json.RawMessage) *ResourceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// AppendStatus appends value to the "status" field.
func (_u *ResourceUpdate) AppendStatus(v json.RawMessage) *ResourceUpdate {
	_u.mutation.AppendStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ResourceUpdate) ClearStatus() *ResourceUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdate) SetUpdatedAt(v time.Time) *ResourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResourceVersion sets the "resource_version" field.
func (_u *ResourceUpdate) SetResourceVersion(v string) *ResourceUpdate {
	_u.mutation.SetResourceVersion(v)
	return _u
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableResourceVersion(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetResourceVersion(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *ResourceUpdate) SetNamespace(v string) *ResourceUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableNamespace(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// ClearNamespace clears the value of the "namespace" field.
func (_u *ResourceUpdate) ClearNamespace() *ResourceUpdate {
	_u.mutation.ClearNamespace()
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ResourceUpdate) SetResourceID(v string) *ResourceUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ResourceUpdate) SetNillableResourceID(v *string) *ResourceUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *ResourceUpdate) ClearResourceID() *ResourceUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_u *ResourceUpdate) AddLabelIDs(ids ...int) *ResourceUpdate {
	_u.mutation.AddLabelIDs(ids...)
	return _u
}

// AddLabels adds the "labels" edges to the Label entity.
func (_u *ResourceUpdate) AddLabels(v ...*Label) *ResourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelIDs(ids...)
}

// AddAnnotationIDs adds the "annotations" edge to the Annotation entity by IDs.
func (_u *ResourceUpdate) AddAnnotationIDs(ids ...int) *ResourceUpdate {
	_u.mutation.AddAnnotationIDs(ids...)
	return _u
}

// AddAnnotations adds the "annotations" edges to the Annotation entity.
func (_u *ResourceUpdate) AddAnnotations(v ...*Annotation) *ResourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnotationIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdate) Mutation() *ResourceMutation {
	return _u.mutation
}

// ClearLabels clears all "labels" edges to the Label entity.
func (_u *ResourceUpdate) ClearLabels() *ResourceUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// RemoveLabelIDs removes the "labels" edge to Label entities by IDs.
func (_u *ResourceUpdate) RemoveLabelIDs(ids ...int) *ResourceUpdate {
	_u.mutation.RemoveLabelIDs(ids...)
	return _u
}

// RemoveLabels removes "labels" edges to Label entities.
func (_u *ResourceUpdate) RemoveLabels(v ...*Label) *ResourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelIDs(ids...)
}

// ClearAnnotations clears all "annotations" edges to the Annotation entity.
func (_u *ResourceUpdate) ClearAnnotations() *ResourceUpdate {
	_u.mutation.ClearAnnotations()
	return _u
}

// RemoveAnnotationIDs removes the "annotations" edge to Annotation entities by IDs.
func (_u *ResourceUpdate) RemoveAnnotationIDs(ids ...int) *ResourceUpdate {
	_u.mutation.RemoveAnnotationIDs(ids...)
	return _u
}

// RemoveAnnotations removes "annotations" edges to Annotation entities.
func (_u *ResourceUpdate) RemoveAnnotations(v ...*Annotation) *ResourceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnotationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := resource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Resource.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := resource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Resource.resource_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(resource.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(resource.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(resource.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Spec(); ok {
		_spec.SetField(resource.FieldSpec, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpec(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resource.FieldSpec, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStatus(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resource.FieldStatus, value)
		})
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(resource.FieldStatus, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResourceVersion(); ok {
		_spec.SetField(resource.FieldResourceVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(resource.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.NamespaceCleared() {
		_spec.ClearField(resource.FieldNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(resource.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(resource.FieldResourceID, field.TypeString)
	}
	if _u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelsIDs(); len(nodes) > 0 && !_u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnotationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnotationsIDs(); len(nodes) > 0 && !_u.mutation.AnnotationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnotationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResourceUpdateOne is the builder for updating a single Resource entity.
type ResourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResourceMutation
}

// SetName sets the "name" field.
func (_u *ResourceUpdateOne) SetName(v string) *ResourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableName(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAPIVersion sets the "api_version" field.
func (_u *ResourceUpdateOne) SetAPIVersion(v string) *ResourceUpdateOne {
	_u.mutation.SetAPIVersion(v)
	return _u
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableAPIVersion(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetAPIVersion(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ResourceUpdateOne) SetKind(v string) *ResourceUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableKind(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ResourceUpdateOne) SetResourceType(v string) *ResourceUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableResourceType(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetSpec sets the "spec" field.
func (_u *ResourceUpdateOne) SetSpec(v json.RawMessage) *ResourceUpdateOne {
	_u.mutation.SetSpec(v)
	return _u
}

// AppendSpec appends value to the "spec" field.
func (_u *ResourceUpdateOne) AppendSpec(v json.RawMessage) *ResourceUpdateOne {
	_u.mutation.AppendSpec(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResourceUpdateOne) SetStatus(v json.RawMessage) *ResourceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// AppendStatus appends value to the "status" field.
func (_u *ResourceUpdateOne) AppendStatus(v json.RawMessage) *ResourceUpdateOne {
	_u.mutation.AppendStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ResourceUpdateOne) ClearStatus() *ResourceUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResourceUpdateOne) SetUpdatedAt(v time.Time) *ResourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetResourceVersion sets the "resource_version" field.
func (_u *ResourceUpdateOne) SetResourceVersion(v string) *ResourceUpdateOne {
	_u.mutation.SetResourceVersion(v)
	return _u
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableResourceVersion(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetResourceVersion(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *ResourceUpdateOne) SetNamespace(v string) *ResourceUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableNamespace(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// ClearNamespace clears the value of the "namespace" field.
func (_u *ResourceUpdateOne) ClearNamespace() *ResourceUpdateOne {
	_u.mutation.ClearNamespace()
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ResourceUpdateOne) SetResourceID(v string) *ResourceUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ResourceUpdateOne) SetNillableResourceID(v *string) *ResourceUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *ResourceUpdateOne) ClearResourceID() *ResourceUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_u *ResourceUpdateOne) AddLabelIDs(ids ...int) *ResourceUpdateOne {
	_u.mutation.AddLabelIDs(ids...)
	return _u
}

// AddLabels adds the "labels" edges to the Label entity.
func (_u *ResourceUpdateOne) AddLabels(v ...*Label) *ResourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelIDs(ids...)
}

// AddAnnotationIDs adds the "annotations" edge to the Annotation entity by IDs.
func (_u *ResourceUpdateOne) AddAnnotationIDs(ids ...int) *ResourceUpdateOne {
	_u.mutation.AddAnnotationIDs(ids...)
	return _u
}

// AddAnnotations adds the "annotations" edges to the Annotation entity.
func (_u *ResourceUpdateOne) AddAnnotations(v ...*Annotation) *ResourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnotationIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_u *ResourceUpdateOne) Mutation() *ResourceMutation {
	return _u.mutation
}

// ClearLabels clears all "labels" edges to the Label entity.
func (_u *ResourceUpdateOne) ClearLabels() *ResourceUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// RemoveLabelIDs removes the "labels" edge to Label entities by IDs.
func (_u *ResourceUpdateOne) RemoveLabelIDs(ids ...int) *ResourceUpdateOne {
	_u.mutation.RemoveLabelIDs(ids...)
	return _u
}

// RemoveLabels removes "labels" edges to Label entities.
func (_u *ResourceUpdateOne) RemoveLabels(v ...*Label) *ResourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelIDs(ids...)
}

// ClearAnnotations clears all "annotations" edges to the Annotation entity.
func (_u *ResourceUpdateOne) ClearAnnotations() *ResourceUpdateOne {
	_u.mutation.ClearAnnotations()
	return _u
}

// RemoveAnnotationIDs removes the "annotations" edge to Annotation entities by IDs.
func (_u *ResourceUpdateOne) RemoveAnnotationIDs(ids ...int) *ResourceUpdateOne {
	_u.mutation.RemoveAnnotationIDs(ids...)
	return _u
}

// RemoveAnnotations removes "annotations" edges to Annotation entities.
func (_u *ResourceUpdateOne) RemoveAnnotations(v ...*Annotation) *ResourceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnotationIDs(ids...)
}

// Where appends a list predicates to the ResourceUpdate builder.
func (_u *ResourceUpdateOne) Where(ps ...predicate.Resource) *ResourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResourceUpdateOne) Select(field string, fields ...string) *ResourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resource entity.
func (_u *ResourceUpdateOne) Save(ctx context.Context) (*Resource, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResourceUpdateOne) SaveX(ctx context.Context) *Resource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := resource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Resource.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := resource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Resource.resource_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ResourceUpdateOne) sqlSave(ctx context.Context) (_node *Resource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resource.Table, resource.Columns, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resource.FieldID)
		for _, f := range fields {
			if !resource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIVersion(); ok {
		_spec.SetField(resource.FieldAPIVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(resource.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(resource.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Spec(); ok {
		_spec.SetField(resource.FieldSpec, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpec(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resource.FieldSpec, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedStatus(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, resource.FieldStatus, value)
		})
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(resource.FieldStatus, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ResourceVersion(); ok {
		_spec.SetField(resource.FieldResourceVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(resource.FieldNamespace, field.TypeString, value)
	}
	if _u.mutation.NamespaceCleared() {
		_spec.ClearField(resource.FieldNamespace, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(resource.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(resource.FieldResourceID, field.TypeString)
	}
	if _u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelsIDs(); len(nodes) > 0 && !_u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnotationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnotationsIDs(); len(nodes) > 0 && !_u.mutation.AnnotationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnotationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Resource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
