// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/annotation"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/label"
	"github.com/OpenCHAMI/inventory-service/internal/storage/ent/resource"
)

// ResourceCreate is the builder for creating a Resource entity.
type ResourceCreate struct {
	config
	mutation *ResourceMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (_c *ResourceCreate) SetUID(v string) *ResourceCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ResourceCreate) SetName(v string) *ResourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAPIVersion sets the "api_version" field.
func (_c *ResourceCreate) SetAPIVersion(v string) *ResourceCreate {
	_c.mutation.SetAPIVersion(v)
	return _c
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableAPIVersion(v *string) *ResourceCreate {
	if v != nil {
		_c.SetAPIVersion(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ResourceCreate) SetKind(v string) *ResourceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *ResourceCreate) SetResourceType(v string) *ResourceCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetSpec sets the "spec" field.
func (_c *ResourceCreate) SetSpec(v json.RawMessage) *ResourceCreate {
	_c.mutation.SetSpec(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResourceCreate) SetStatus(v json.RawMessage) *ResourceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceCreate) SetCreatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableCreatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceCreate) SetUpdatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableUpdatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetResourceVersion sets the "resource_version" field.
func (_c *ResourceCreate) SetResourceVersion(v string) *ResourceCreate {
	_c.mutation.SetResourceVersion(v)
	return _c
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableResourceVersion(v *string) *ResourceCreate {
	if v != nil {
		_c.SetResourceVersion(*v)
	}
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *ResourceCreate) SetNamespace(v string) *ResourceCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableNamespace(v *string) *ResourceCreate {
	if v != nil {
		_c.SetNamespace(*v)
	}
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ResourceCreate) SetResourceID(v string) *ResourceCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableResourceID(v *string) *ResourceCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_c *ResourceCreate) AddLabelIDs(ids ...int) *ResourceCreate {
	_c.mutation.AddLabelIDs(ids...)
	return _c
}

// AddLabels adds the "labels" edges to the Label entity.
func (_c *ResourceCreate) AddLabels(v ...*Label) *ResourceCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLabelIDs(ids...)
}

// AddAnnotationIDs adds the "annotations" edge to the Annotation entity by IDs.
func (_c *ResourceCreate) AddAnnotationIDs(ids ...int) *ResourceCreate {
	_c.mutation.AddAnnotationIDs(ids...)
	return _c
}

// AddAnnotations adds the "annotations" edges to the Annotation entity.
func (_c *ResourceCreate) AddAnnotations(v ...*Annotation) *ResourceCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnnotationIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (_c *ResourceCreate) Mutation() *ResourceMutation {
	return _c.mutation
}

// Save creates the Resource in the database.
func (_c *ResourceCreate) Save(ctx context.Context) (*Resource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceCreate) SaveX(ctx context.Context) *Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceCreate) defaults() {
	if _, ok := _c.mutation.APIVersion(); !ok {
		v := resource.DefaultAPIVersion
		_c.mutation.SetAPIVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ResourceVersion(); !ok {
		v := resource.DefaultResourceVersion
		_c.mutation.SetResourceVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceCreate) check() error {
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Resource.uid"`)}
	}
	if v, ok := _c.mutation.UID(); ok {
		if err := resource.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Resource.uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Resource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIVersion(); !ok {
		return &ValidationError{Name: "api_version", err: errors.New(`ent: missing required field "Resource.api_version"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Resource.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := resource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Resource.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "Resource.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := resource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Resource.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Spec(); !ok {
		return &ValidationError{Name: "spec", err: errors.New(`ent: missing required field "Resource.spec"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Resource.updated_at"`)}
	}
	if _, ok := _c.mutation.ResourceVersion(); !ok {
		return &ValidationError{Name: "resource_version", err: errors.New(`ent: missing required field "Resource.resource_version"`)}
	}
	return nil
}

func (_c *ResourceCreate) sqlSave(ctx context.Context) (*Resource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceCreate) createSpec() (*Resource, *sqlgraph.CreateSpec) {
	var (
		_node = &Resource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resource.Table, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(resource.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.APIVersion(); ok {
		_spec.SetField(resource.FieldAPIVersion, field.TypeString, value)
		_node.APIVersion = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(resource.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(resource.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.Spec(); ok {
		_spec.SetField(resource.FieldSpec, field.TypeJSON, value)
		_node.Spec = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeJSON, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ResourceVersion(); ok {
		_spec.SetField(resource.FieldResourceVersion, field.TypeString, value)
		_node.ResourceVersion = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(resource.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(resource.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if nodes := _c.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnnotationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResourceCreateBulk is the builder for creating many Resource entities in bulk.
type ResourceCreateBulk struct {
	config
	err      error
	builders []*ResourceCreate
}

// Save creates the Resource entities in the database.
func (_c *ResourceCreateBulk) Save(ctx context.Context) ([]*Resource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Resource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceCreateBulk) SaveX(ctx context.Context) []*Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
