// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// NOTE: This file is a template without Go template syntax because it provides
// a generic, reusable Ent schema that works for all Fabrica projects without
// customization. It must be generated into each project because Ent's code
// generator (go generate) requires schemas to be present locally to generate
// the type-safe database client code.

package schema

import (
	"encoding/json"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Resource holds the schema definition for the generic resource entity.
// This schema stores Kubernetes-style resources with Spec and Status as JSON.
type Resource struct {
	ent.Schema
}

// Fields of the Resource.
func (Resource) Fields() []ent.Field {
	return []ent.Field{
		// Identity
		field.String("uid").
			Unique().
			Immutable().
			NotEmpty().
			Comment("Unique identifier (e.g., dev-1a2b3c4d)"),

		field.String("name").
			NotEmpty().
			MaxLen(253).
			Comment("Human-readable name"),

		// Resource type information
		field.String("api_version").
			Default("v1").
			Comment("API version (e.g., v1, v2beta1)"),

		field.String("kind").
			NotEmpty().
			Comment("Resource kind (e.g., Device, Node)"),

		field.String("resource_type").
			NotEmpty().
			Comment("Resource type for indexing"),

		// Kubernetes-style Spec and Status (stored as JSON)
		field.JSON("spec", json.RawMessage{}).
			Comment("Desired state of the resource"),

		field.JSON("status", json.RawMessage{}).
			Optional().
			Comment("Observed state of the resource"),

		// Timestamps
		field.Time("created_at").
			Immutable().
			Default(time.Now).
			Comment("Resource creation timestamp"),

		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now).
			Comment("Last update timestamp"),

		// Versioning for optimistic concurrency control
		field.String("resource_version").
			Default("1").
			Comment("Resource version for ETags and optimistic locking"),

		// Optional namespace for multi-tenancy
		field.String("namespace").
			Optional().
			Comment("Namespace for multi-tenancy"),

		// Optional identifier that is unique within a resource type.
		// What is used for the identifier is specific to each type of resource.
		// It allows for efficient lookups by this ID without needing to parse the JSON Spec.
		field.String("resource_id").
			Optional().
			Comment("Identifier that along with the resource type is unique."),
	}
}

// Edges of the Resource.
func (Resource) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("labels", Label.Type).
			Comment("Labels for selection and grouping"),
		edge.To("annotations", Annotation.Type).
			Comment("Annotations for arbitrary metadata"),
	}
}

// Indexes of the Resource.
func (Resource) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("uid").Unique(),
		index.Fields("resource_type", "name"),
		index.Fields("resource_type", "namespace"),
		index.Fields("kind"),
		index.Fields("resource_type", "resource_id").Unique(),
	}
}
