// Code generated by Fabrica v0.4.0-5-g442df75. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-02T12:26:26-06:00
//
// # Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for ComponentEndpoint resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /componentendpoints (list all componentendpoints)
//   - GET /componentendpoints/{uid} (get specific ComponentEndpoint)
//   - POST /componentendpoints (create new ComponentEndpoint)
//   - PUT /componentendpoints/{uid} (update ComponentEndpoint spec)
//   - PATCH /componentendpoints/{uid} (patch ComponentEndpoint spec)
//   - DELETE /componentendpoints/{uid} (delete ComponentEndpoint)
//   - PUT /componentendpoints/{uid}/status (update ComponentEndpoint status)
//   - PATCH /componentendpoints/{uid}/status (patch ComponentEndpoint status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses plugins.Store.LoadComponentEndpoint*/SaveComponentEndpoint*/DeleteComponentEndpoint*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: plugins.Store.LoadComponentEndpointWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/OpenCHAMI/smd2/apis/smd2.openchami.org/v1"
	"github.com/OpenCHAMI/smd2/cmd/plugins"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
)

// GetComponentEndpoints returns all ComponentEndpoint resources
func GetComponentEndpoints(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	componentendpoints, err := plugins.Store.LoadAllComponentEndpoints(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load componentendpoints: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, componentendpoints)
}

// GetComponentEndpoint returns a specific ComponentEndpoint resource by UID
func GetComponentEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ComponentEndpoint UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace plugins.Store.LoadComponentEndpoint() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	componentEndpoint, err := plugins.Store.LoadComponentEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ComponentEndpoint not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, componentEndpoint)
}

// CreateComponentEndpoint creates a new ComponentEndpoint resource
func CreateComponentEndpoint(w http.ResponseWriter, r *http.Request) {
	var req CreateComponentEndpointRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("ComponentEndpoint")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	componentEndpoint := &v1.ComponentEndpoint{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "ComponentEndpoint",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	componentEndpoint.Metadata = req.Metadata
	componentEndpoint.Metadata.UID = uid
	now := time.Now()
	componentEndpoint.Metadata.CreatedAt = now
	componentEndpoint.Metadata.UpdatedAt = now

	// Set labels and annotations
	if componentEndpoint.Metadata.Labels == nil {
		componentEndpoint.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		componentEndpoint.Metadata.Labels[k] = v
	}
	if componentEndpoint.Metadata.Annotations == nil {
		componentEndpoint.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		componentEndpoint.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), componentEndpoint); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := plugins.Store.SaveComponentEndpoint(r.Context(), componentEndpoint); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ComponentEndpoint: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "ComponentEndpoint", componentEndpoint.Metadata.UID, componentEndpoint.Metadata.Name, componentEndpoint); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for ComponentEndpoint %s: %v\n", componentEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, componentEndpoint)
}

// UpdateComponentEndpoint updates the spec of an existing ComponentEndpoint resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //componentendpoints/{uid}/status to update status.
func UpdateComponentEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ComponentEndpoint UID is required"))
		return
	}

	componentEndpoint, err := plugins.Store.LoadComponentEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ComponentEndpoint not found: %w", err))
		return
	}

	var req UpdateComponentEndpointRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		componentEndpoint.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	componentEndpoint.Spec = req.AsSpec()

	// Update labels and annotations
	if componentEndpoint.Metadata.Labels == nil {
		componentEndpoint.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		componentEndpoint.Metadata.Labels[k] = v
	}
	if componentEndpoint.Metadata.Annotations == nil {
		componentEndpoint.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		componentEndpoint.Metadata.Annotations[k] = v
	}

	// Update timestamp
	componentEndpoint.Metadata.UpdatedAt = time.Now()

	if err := plugins.Store.SaveComponentEndpoint(r.Context(), componentEndpoint); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ComponentEndpoint: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": componentEndpoint.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "ComponentEndpoint", componentEndpoint.Metadata.UID, componentEndpoint.Metadata.Name, componentEndpoint, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for ComponentEndpoint %s: %v\n", componentEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, componentEndpoint)
}

// PatchComponentEndpoint patches an existing ComponentEndpoint resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchComponentEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ComponentEndpoint UID is required"))
		return
	}

	componentEndpoint, err := plugins.Store.LoadComponentEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ComponentEndpoint not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(componentEndpoint.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &componentEndpoint.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	componentEndpoint.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := plugins.Store.SaveComponentEndpoint(r.Context(), componentEndpoint); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched ComponentEndpoint: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": componentEndpoint.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "ComponentEndpoint", componentEndpoint.Metadata.UID, componentEndpoint.Metadata.Name, componentEndpoint, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for ComponentEndpoint %s: %v\n", componentEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, componentEndpoint)
}

// UpdateComponentEndpointStatus updates only the status of a ComponentEndpoint resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateComponentEndpointStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ComponentEndpoint UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := plugins.Store.LoadComponentEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ComponentEndpoint not found: %w", err))
		return
	}

	var statusUpdate v1.ComponentEndpointStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := plugins.Store.SaveComponentEndpoint(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ComponentEndpoint status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "ComponentEndpoint", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for ComponentEndpoint %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchComponentEndpointStatus patches only the status of a ComponentEndpoint resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchComponentEndpointStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ComponentEndpoint UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := plugins.Store.LoadComponentEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ComponentEndpoint not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := plugins.Store.SaveComponentEndpoint(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched ComponentEndpoint status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "ComponentEndpoint", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for ComponentEndpoint %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteComponentEndpoint deletes a ComponentEndpoint resource
func DeleteComponentEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ComponentEndpoint UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	componentEndpoint, err := plugins.Store.LoadComponentEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ComponentEndpoint not found: %w", err))
		return
	}

	if err := plugins.Store.DeleteComponentEndpoint(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete ComponentEndpoint: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "ComponentEndpoint", componentEndpoint.Metadata.UID, componentEndpoint.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for ComponentEndpoint %s: %v\n", componentEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "ComponentEndpoint deleted successfully",
		UID:     uid,
	})
}
