// Code generated by Fabrica v0.4.0-5-g442df75. DO NOT EDIT.
// Template: init/main.go.tmpl
// Generated: 2026-04-02T12:25:52-06:00
//
// Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/OpenCHAMI/smd2/cmd/controllers"
	"github.com/OpenCHAMI/smd2/cmd/plugins"
	_ "github.com/OpenCHAMI/smd2/pkg/apiversion"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/openchami/fabrica/pkg/versioning"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/OpenCHAMI/smd2/internal/storage"

	"github.com/OpenCHAMI/smd2/internal/storage/ent"
	"github.com/OpenCHAMI/smd2/internal/storage/ent/migrate"

	_ "github.com/mattn/go-sqlite3"
)

// Config holds all configuration for the service
type Config struct {
	// Server Configuration
	Port         int    `mapstructure:"port"`
	Host         string `mapstructure:"host"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	IdleTimeout  int    `mapstructure:"idle_timeout"`

	// Storage Configuration

	DatabaseURL string `mapstructure:"database-url"`

	// Feature Flags

	Debug bool `mapstructure:"debug"`
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Port:         8080,
		Host:         "0.0.0.0",
		ReadTimeout:  15,
		WriteTimeout: 15,
		IdleTimeout:  60,

		DatabaseURL: "file:./data.db?cache=shared&_fk=1",

		Debug: false,
	}
}

var (
	cfgFile string
	config  *Config
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "smd2",
	Short: "",
	Long:  `smd2 - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the smd2 server",
	Long:  `Start the smd2 HTTP server with the configured options`,
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.smd2.yaml)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")

	// Server flags
	serveCmd.Flags().IntP("port", "p", 8080, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().Int("read-timeout", 15, "Read timeout in seconds")
	serveCmd.Flags().Int("write-timeout", 15, "Write timeout in seconds")
	serveCmd.Flags().Int("idle-timeout", 60, "Idle timeout in seconds")

	serveCmd.Flags().String("database-url", "", "Database connection URL")

	// Bind flags to viper
	viper.BindPFlags(serveCmd.Flags())
	viper.BindPFlags(rootCmd.PersistentFlags())

	// Add subcommands
	rootCmd.AddCommand(serveCmd)

	rootCmd.AddCommand(versionCmd)

	// Generated by Fabrica v0.4.0+: export and import commands (Ent storage only)

	rootCmd.AddCommand(newExportCommand())
	rootCmd.AddCommand(newImportCommand())

	plugins.Store = &controllers.EntStorage{}
}

func initConfig() {
	config = DefaultConfig()

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		// Search for config in home directory
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".smd2")
	}

	// Environment variables
	viper.SetEnvPrefix("SMD2")
	viper.AutomaticEnv()

	// Read config file if it exists
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}

	// Unmarshal config
	if err := viper.Unmarshal(config); err != nil {
		log.Fatalf("Unable to decode into config struct: %v", err)
	}

	// Set debug logging
	if config.Debug {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
		log.Println("Debug logging enabled")
	}
}

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting smd2 server...")

	// Initialize storage backend

	// Connect to database
	client, err := ent.Open("sqlite3", config.DatabaseURL)
	if err != nil {
		return fmt.Errorf("failed opening connection to sqlite3: %w", err)
	}
	defer client.Close()

	// Run auto-migration
	ctx := context.Background()
	if err := client.Schema.Create(
		ctx,
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
	); err != nil {
		return fmt.Errorf("failed creating schema resources: %w", err)
	}
	log.Println("Database schema migrated successfully")

	// Set Ent client for storage operations
	storage.SetEntClient(client)
	log.Printf("Ent storage initialized with sqlite3 database")

	// Register resource prefixes for UID generation
	// This is required before any handlers can create resources
	if err := registerResourcePrefixes(); err != nil {
		return fmt.Errorf("failed to register resource prefixes: %w", err)
	}

	// Setup router
	r := chi.NewRouter()

	// Add middleware
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)

	// Version negotiation (Accept header `version=` or URL strategy)
	// Initialize and use global version registry when versioning is enabled.
	// Note: VersionNegotiationMiddleware currently uses versioning.VersionRegistry
	// Versioning support will be fully wired in a future update.
	r.Use(versioning.VersionNegotiationMiddleware(versioning.GlobalVersionRegistry, nil))

	if config.Debug {
		r.Mount("/debug", middleware.Profiler())
	}

	// Public endpoints (bypass AuthN/AuthZ)
	r.Group(func(public chi.Router) {
		// Service health (always public)
		public.Get("/health", healthHandler)
	})

	// Protected endpoints (API handlers)
	r.Group(func(protected chi.Router) {

		// Register routes - generated by 'fabrica generate'
		RegisterGeneratedRoutes(protected)
		RegisterCsmRoutes(protected)
	})

	// Create HTTP server
	addr := fmt.Sprintf("%s:%d", config.Host, config.Port)
	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  time.Duration(config.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(config.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(config.IdleTimeout) * time.Second,
	}

	// Start server in goroutine
	go func() {
		log.Printf("Server starting on %s", addr)

		log.Printf("Storage: sqlite3 database")

		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Server shutting down...")

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Println("Server exited")
	return nil
}

// Health check handler
func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"healthy","service":"smd2"}`))
}

// registerResourcePrefixes is defined in routes_generated.go

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number",
	Long:  `Print the version number of smd2`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("smd2 v1.0.0")
	},
}
