// Code generated by Fabrica v0.4.0-5-g442df75. DO NOT EDIT.
// Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains request/response models for REST API operations.
// Generated from: pkg/codegen/templates/models.go.tmpl
//
// To modify request/response models:
//  1. Edit the template file: pkg/codegen/templates/models.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated models for each resource:
//   - ResourceResponse: Single resource response (alias to resource type)
//   - ResourcesResponse: List of resources with pagination info
//   - CreateResourceRequest: Create operation request body
//   - UpdateResourceRequest: Update operation request body
//   - DeleteResponse: Delete operation response
//
// Request structure:
//   - Embeds resource Spec fields inline (json:",inline")
//   - Includes metadata fields (Name, Labels, Annotations)
//   - Uses validation tags for required fields
//
// To add custom validation:
//  1. Add validation tags to template (e.g., validate:"required,email")
//  2. Implement validation middleware in handlers
//
// To add additional fields:
//  1. Modify Create/Update request structs in template
//  2. Update corresponding handlers to process new fields
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	v1 "github.com/OpenCHAMI/smd2/apis/smd2.openchami.org/v1"
	"github.com/openchami/fabrica/pkg/fabrica"
)

// ComponentResponse represents the response for Component operations
type ComponentResponse = v1.Component

// CreateComponentRequest represents a request to create a Component
type CreateComponentRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.ComponentSpec  `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateComponentRequest) AsSpec() v1.ComponentSpec {
	return r.Spec
}

// UpdateComponentRequest represents a request to update a Component
type UpdateComponentRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.ComponentSpec  `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateComponentRequest) AsSpec() v1.ComponentSpec {
	return r.Spec
}

// ComponentEndpointResponse represents the response for ComponentEndpoint operations
type ComponentEndpointResponse = v1.ComponentEndpoint

// CreateComponentEndpointRequest represents a request to create a ComponentEndpoint
type CreateComponentEndpointRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata" validate:"required"`
	Spec        v1.ComponentEndpointSpec `json:"spec" validate:"required"`
	Labels      map[string]string        `json:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateComponentEndpointRequest) AsSpec() v1.ComponentEndpointSpec {
	return r.Spec
}

// UpdateComponentEndpointRequest represents a request to update a ComponentEndpoint
type UpdateComponentEndpointRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata,omitempty"`
	Spec        v1.ComponentEndpointSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string        `json:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateComponentEndpointRequest) AsSpec() v1.ComponentEndpointSpec {
	return r.Spec
}

// EthernetInterfaceResponse represents the response for EthernetInterface operations
type EthernetInterfaceResponse = v1.EthernetInterface

// CreateEthernetInterfaceRequest represents a request to create a EthernetInterface
type CreateEthernetInterfaceRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata" validate:"required"`
	Spec        v1.EthernetInterfaceSpec `json:"spec" validate:"required"`
	Labels      map[string]string        `json:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateEthernetInterfaceRequest) AsSpec() v1.EthernetInterfaceSpec {
	return r.Spec
}

// UpdateEthernetInterfaceRequest represents a request to update a EthernetInterface
type UpdateEthernetInterfaceRequest struct {
	Metadata    fabrica.Metadata         `json:"metadata,omitempty"`
	Spec        v1.EthernetInterfaceSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string        `json:"labels,omitempty"`
	Annotations map[string]string        `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateEthernetInterfaceRequest) AsSpec() v1.EthernetInterfaceSpec {
	return r.Spec
}

// GroupResponse represents the response for Group operations
type GroupResponse = v1.Group

// CreateGroupRequest represents a request to create a Group
type CreateGroupRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.GroupSpec      `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateGroupRequest) AsSpec() v1.GroupSpec {
	return r.Spec
}

// UpdateGroupRequest represents a request to update a Group
type UpdateGroupRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.GroupSpec      `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateGroupRequest) AsSpec() v1.GroupSpec {
	return r.Spec
}

// RedfishEndpointResponse represents the response for RedfishEndpoint operations
type RedfishEndpointResponse = v1.RedfishEndpoint

// CreateRedfishEndpointRequest represents a request to create a RedfishEndpoint
type CreateRedfishEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" validate:"required"`
	Spec        v1.RedfishEndpointSpec `json:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateRedfishEndpointRequest) AsSpec() v1.RedfishEndpointSpec {
	return r.Spec
}

// UpdateRedfishEndpointRequest represents a request to update a RedfishEndpoint
type UpdateRedfishEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty"`
	Spec        v1.RedfishEndpointSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateRedfishEndpointRequest) AsSpec() v1.RedfishEndpointSpec {
	return r.Spec
}

// ServiceEndpointResponse represents the response for ServiceEndpoint operations
type ServiceEndpointResponse = v1.ServiceEndpoint

// CreateServiceEndpointRequest represents a request to create a ServiceEndpoint
type CreateServiceEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata" validate:"required"`
	Spec        v1.ServiceEndpointSpec `json:"spec" validate:"required"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateServiceEndpointRequest) AsSpec() v1.ServiceEndpointSpec {
	return r.Spec
}

// UpdateServiceEndpointRequest represents a request to update a ServiceEndpoint
type UpdateServiceEndpointRequest struct {
	Metadata    fabrica.Metadata       `json:"metadata,omitempty"`
	Spec        v1.ServiceEndpointSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string      `json:"labels,omitempty"`
	Annotations map[string]string      `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateServiceEndpointRequest) AsSpec() v1.ServiceEndpointSpec {
	return r.Spec
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message,omitempty"`
	Code    int    `json:"code,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}

// Helper functions for handlers

// respondJSON sends a JSON response
func respondJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(data); err != nil {
		http.Error(w, fmt.Sprintf("failed to encode response: %v", err), http.StatusInternalServerError)
	}
}

// respondError sends an error response
func respondError(w http.ResponseWriter, status int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	response := ErrorResponse{
		Error: err.Error(),
		Code:  status,
	}
	json.NewEncoder(w).Encode(response)
}
