// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /components (Component operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
)

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {

	// Component routes
	r.Route("/components", func(r chi.Router) {
		r.Get("/", GetComponents)
		r.Post("/", CreateComponent)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetComponent)
			r.Put("/", UpdateComponent)
			r.Patch("/", PatchComponent)
			r.Delete("/", DeleteComponent)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateComponentStatus)
				r.Patch("/", PatchComponentStatus)
			})
		})
	})

	// OpenAPI documentation routes
	r.Get("/openapi.json", ServeOpenAPISpec)
	r.Get("/docs", ServeSwaggerUI)
}
