// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /components (Component operations)
//   - /componentendpoints (ComponentEndpoint operations)
//   - /ethernetinterfaces (EthernetInterface operations)
//   - /groups (Group operations)
//   - /redfishendpoints (RedfishEndpoint operations)
//   - /serviceendpoints (ServiceEndpoint operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("Component", "component")

	resource.RegisterResourcePrefix("ComponentEndpoint", "componentendpoint")

	resource.RegisterResourcePrefix("EthernetInterface", "ethernetinterface")

	resource.RegisterResourcePrefix("Group", "group")

	resource.RegisterResourcePrefix("RedfishEndpoint", "redfishendpoint")

	resource.RegisterResourcePrefix("ServiceEndpoint", "serviceendpoint")

	return nil
}

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {
	// Public endpoints (bypass AuthN/AuthZ)
	r.Group(func(public chi.Router) {
		// OpenAPI documentation routes
		public.Get("/openapi.json", ServeOpenAPISpec)
		public.Get("/docs", ServeSwaggerUI)
	})

	// Protected endpoints (resource APIs)
	r.Group(func(protected chi.Router) {

		// Component routes
		protected.Route("/components", func(r chi.Router) {
			r.Get("/", GetComponents)
			r.Post("/", CreateComponent)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetComponent)
				r.Put("/", UpdateComponent)
				r.Patch("/", PatchComponent)
				r.Delete("/", DeleteComponent)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateComponentStatus)
					r.Patch("/", PatchComponentStatus)
				})
			})
		})

		// ComponentEndpoint routes
		protected.Route("/componentendpoints", func(r chi.Router) {
			r.Get("/", GetComponentEndpoints)
			r.Post("/", CreateComponentEndpoint)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetComponentEndpoint)
				r.Put("/", UpdateComponentEndpoint)
				r.Patch("/", PatchComponentEndpoint)
				r.Delete("/", DeleteComponentEndpoint)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateComponentEndpointStatus)
					r.Patch("/", PatchComponentEndpointStatus)
				})
			})
		})

		// EthernetInterface routes
		protected.Route("/ethernetinterfaces", func(r chi.Router) {
			r.Get("/", GetEthernetInterfaces)
			r.Post("/", CreateEthernetInterface)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetEthernetInterface)
				r.Put("/", UpdateEthernetInterface)
				r.Patch("/", PatchEthernetInterface)
				r.Delete("/", DeleteEthernetInterface)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateEthernetInterfaceStatus)
					r.Patch("/", PatchEthernetInterfaceStatus)
				})
			})
		})

		// Group routes
		protected.Route("/groups", func(r chi.Router) {
			r.Get("/", GetGroups)
			r.Post("/", CreateGroup)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetGroup)
				r.Put("/", UpdateGroup)
				r.Patch("/", PatchGroup)
				r.Delete("/", DeleteGroup)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateGroupStatus)
					r.Patch("/", PatchGroupStatus)
				})
			})
		})

		// RedfishEndpoint routes
		protected.Route("/redfishendpoints", func(r chi.Router) {
			r.Get("/", GetRedfishEndpoints)
			r.Post("/", CreateRedfishEndpoint)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetRedfishEndpoint)
				r.Put("/", UpdateRedfishEndpoint)
				r.Patch("/", PatchRedfishEndpoint)
				r.Delete("/", DeleteRedfishEndpoint)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateRedfishEndpointStatus)
					r.Patch("/", PatchRedfishEndpointStatus)
				})
			})
		})

		// ServiceEndpoint routes
		protected.Route("/serviceendpoints", func(r chi.Router) {
			r.Get("/", GetServiceEndpoints)
			r.Post("/", CreateServiceEndpoint)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetServiceEndpoint)
				r.Put("/", UpdateServiceEndpoint)
				r.Patch("/", PatchServiceEndpoint)
				r.Delete("/", DeleteServiceEndpoint)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateServiceEndpointStatus)
					r.Patch("/", PatchServiceEndpointStatus)
				})
			})
		})

	})
}
