// Code generated by Fabrica v0.4.0-5-g442df75. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-02T12:26:26-06:00
//
// # Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for ServiceEndpoint resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /serviceendpoints (list all serviceendpoints)
//   - GET /serviceendpoints/{uid} (get specific ServiceEndpoint)
//   - POST /serviceendpoints (create new ServiceEndpoint)
//   - PUT /serviceendpoints/{uid} (update ServiceEndpoint spec)
//   - PATCH /serviceendpoints/{uid} (patch ServiceEndpoint spec)
//   - DELETE /serviceendpoints/{uid} (delete ServiceEndpoint)
//   - PUT /serviceendpoints/{uid}/status (update ServiceEndpoint status)
//   - PATCH /serviceendpoints/{uid}/status (patch ServiceEndpoint status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses plugins.Store.LoadServiceEndpoint*/SaveServiceEndpoint*/DeleteServiceEndpoint*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: plugins.Store.LoadServiceEndpointWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/OpenCHAMI/smd2/apis/smd2.openchami.org/v1"
	"github.com/OpenCHAMI/smd2/cmd/plugins"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
)

// GetServiceEndpoints returns all ServiceEndpoint resources
func GetServiceEndpoints(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	serviceendpoints, err := plugins.Store.LoadAllServiceEndpoints(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load serviceendpoints: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, serviceendpoints)
}

// GetServiceEndpoint returns a specific ServiceEndpoint resource by UID
func GetServiceEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ServiceEndpoint UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace plugins.Store.LoadServiceEndpoint() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	serviceEndpoint, err := plugins.Store.LoadServiceEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ServiceEndpoint not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, serviceEndpoint)
}

// CreateServiceEndpoint creates a new ServiceEndpoint resource
func CreateServiceEndpoint(w http.ResponseWriter, r *http.Request) {
	var req CreateServiceEndpointRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("ServiceEndpoint")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	serviceEndpoint := &v1.ServiceEndpoint{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "ServiceEndpoint",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	serviceEndpoint.Metadata = req.Metadata
	serviceEndpoint.Metadata.UID = uid
	now := time.Now()
	serviceEndpoint.Metadata.CreatedAt = now
	serviceEndpoint.Metadata.UpdatedAt = now

	// Set labels and annotations
	if serviceEndpoint.Metadata.Labels == nil {
		serviceEndpoint.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		serviceEndpoint.Metadata.Labels[k] = v
	}
	if serviceEndpoint.Metadata.Annotations == nil {
		serviceEndpoint.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		serviceEndpoint.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), serviceEndpoint); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := plugins.Store.SaveServiceEndpoint(r.Context(), serviceEndpoint); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ServiceEndpoint: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "ServiceEndpoint", serviceEndpoint.Metadata.UID, serviceEndpoint.Metadata.Name, serviceEndpoint); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for ServiceEndpoint %s: %v\n", serviceEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, serviceEndpoint)
}

// UpdateServiceEndpoint updates the spec of an existing ServiceEndpoint resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //serviceendpoints/{uid}/status to update status.
func UpdateServiceEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ServiceEndpoint UID is required"))
		return
	}

	serviceEndpoint, err := plugins.Store.LoadServiceEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ServiceEndpoint not found: %w", err))
		return
	}

	var req UpdateServiceEndpointRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		serviceEndpoint.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	serviceEndpoint.Spec = req.AsSpec()

	// Update labels and annotations
	if serviceEndpoint.Metadata.Labels == nil {
		serviceEndpoint.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		serviceEndpoint.Metadata.Labels[k] = v
	}
	if serviceEndpoint.Metadata.Annotations == nil {
		serviceEndpoint.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		serviceEndpoint.Metadata.Annotations[k] = v
	}

	// Update timestamp
	serviceEndpoint.Metadata.UpdatedAt = time.Now()

	if err := plugins.Store.SaveServiceEndpoint(r.Context(), serviceEndpoint); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ServiceEndpoint: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": serviceEndpoint.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "ServiceEndpoint", serviceEndpoint.Metadata.UID, serviceEndpoint.Metadata.Name, serviceEndpoint, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for ServiceEndpoint %s: %v\n", serviceEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, serviceEndpoint)
}

// PatchServiceEndpoint patches an existing ServiceEndpoint resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchServiceEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ServiceEndpoint UID is required"))
		return
	}

	serviceEndpoint, err := plugins.Store.LoadServiceEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ServiceEndpoint not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(serviceEndpoint.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &serviceEndpoint.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	serviceEndpoint.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := plugins.Store.SaveServiceEndpoint(r.Context(), serviceEndpoint); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched ServiceEndpoint: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": serviceEndpoint.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "ServiceEndpoint", serviceEndpoint.Metadata.UID, serviceEndpoint.Metadata.Name, serviceEndpoint, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for ServiceEndpoint %s: %v\n", serviceEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, serviceEndpoint)
}

// UpdateServiceEndpointStatus updates only the status of a ServiceEndpoint resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateServiceEndpointStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ServiceEndpoint UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := plugins.Store.LoadServiceEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ServiceEndpoint not found: %w", err))
		return
	}

	var statusUpdate v1.ServiceEndpointStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := plugins.Store.SaveServiceEndpoint(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ServiceEndpoint status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "ServiceEndpoint", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for ServiceEndpoint %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchServiceEndpointStatus patches only the status of a ServiceEndpoint resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchServiceEndpointStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ServiceEndpoint UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := plugins.Store.LoadServiceEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ServiceEndpoint not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := plugins.Store.SaveServiceEndpoint(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched ServiceEndpoint status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "ServiceEndpoint", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for ServiceEndpoint %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteServiceEndpoint deletes a ServiceEndpoint resource
func DeleteServiceEndpoint(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ServiceEndpoint UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	serviceEndpoint, err := plugins.Store.LoadServiceEndpoint(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ServiceEndpoint not found: %w", err))
		return
	}

	if err := plugins.Store.DeleteServiceEndpoint(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete ServiceEndpoint: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "ServiceEndpoint", serviceEndpoint.Metadata.UID, serviceEndpoint.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for ServiceEndpoint %s: %v\n", serviceEndpoint.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "ServiceEndpoint deleted successfully",
		UID:     uid,
	})
}
