// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025-2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'make dev' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil)
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"

	v1 "github.com/OpenCHAMI/inventory-service/apis/inventory-service.openchami.org/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
	version    string // Optional API version for Accept/Content-Type headers
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:    c.baseURL,
		httpClient: c.httpClient,
		version:    version,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetComponents retrieves all components
func (c *Client) GetComponents(ctx context.Context) ([]v1.Component, error) {
	var response []v1.Component
	if err := c.doRequest(ctx, "GET", "/components", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetComponent retrieves a specific Component by UID
func (c *Client) GetComponent(ctx context.Context, uid string) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateComponent creates a new Component
func (c *Client) CreateComponent(ctx context.Context, req CreateComponentRequest) (*v1.Component, error) {
	var result v1.Component
	if err := c.doRequest(ctx, "POST", "/components", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponent updates an existing Component
func (c *Client) UpdateComponent(ctx context.Context, uid string, req UpdateComponentRequest) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponent patches an existing Component spec with the specified patch data and content type
func (c *Client) PatchComponent(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentStatus updates only the status of an existing Component
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateComponentStatus(ctx context.Context, uid string, status v1.ComponentStatus) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponentStatus patches only the status of an existing Component
// Supports JSON Merge Patch by default. Use PatchComponentStatusWithType for other patch formats.
func (c *Client) PatchComponentStatus(ctx context.Context, uid string, patchData []byte) (*v1.Component, error) {
	return c.PatchComponentStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchComponentStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchComponentStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Component, error) {
	var result v1.Component
	endpoint := fmt.Sprintf("/components/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteComponent deletes a Component by UID
func (c *Client) DeleteComponent(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/components/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetComponentEndpoints retrieves all componentendpoints
func (c *Client) GetComponentEndpoints(ctx context.Context) ([]v1.ComponentEndpoint, error) {
	var response []v1.ComponentEndpoint
	if err := c.doRequest(ctx, "GET", "/componentendpoints", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetComponentEndpoint retrieves a specific ComponentEndpoint by UID
func (c *Client) GetComponentEndpoint(ctx context.Context, uid string) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateComponentEndpoint creates a new ComponentEndpoint
func (c *Client) CreateComponentEndpoint(ctx context.Context, req CreateComponentEndpointRequest) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	if err := c.doRequest(ctx, "POST", "/componentendpoints", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentEndpoint updates an existing ComponentEndpoint
func (c *Client) UpdateComponentEndpoint(ctx context.Context, uid string, req UpdateComponentEndpointRequest) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponentEndpoint patches an existing ComponentEndpoint spec with the specified patch data and content type
func (c *Client) PatchComponentEndpoint(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateComponentEndpointStatus updates only the status of an existing ComponentEndpoint
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateComponentEndpointStatus(ctx context.Context, uid string, status v1.ComponentEndpointStatus) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchComponentEndpointStatus patches only the status of an existing ComponentEndpoint
// Supports JSON Merge Patch by default. Use PatchComponentEndpointStatusWithType for other patch formats.
func (c *Client) PatchComponentEndpointStatus(ctx context.Context, uid string, patchData []byte) (*v1.ComponentEndpoint, error) {
	return c.PatchComponentEndpointStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchComponentEndpointStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchComponentEndpointStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ComponentEndpoint, error) {
	var result v1.ComponentEndpoint
	endpoint := fmt.Sprintf("/componentendpoints/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteComponentEndpoint deletes a ComponentEndpoint by UID
func (c *Client) DeleteComponentEndpoint(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/componentendpoints/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetEthernetInterfaces retrieves all ethernetinterfaces
func (c *Client) GetEthernetInterfaces(ctx context.Context) ([]v1.EthernetInterface, error) {
	var response []v1.EthernetInterface
	if err := c.doRequest(ctx, "GET", "/ethernetinterfaces", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetEthernetInterface retrieves a specific EthernetInterface by UID
func (c *Client) GetEthernetInterface(ctx context.Context, uid string) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateEthernetInterface creates a new EthernetInterface
func (c *Client) CreateEthernetInterface(ctx context.Context, req CreateEthernetInterfaceRequest) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	if err := c.doRequest(ctx, "POST", "/ethernetinterfaces", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateEthernetInterface updates an existing EthernetInterface
func (c *Client) UpdateEthernetInterface(ctx context.Context, uid string, req UpdateEthernetInterfaceRequest) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchEthernetInterface patches an existing EthernetInterface spec with the specified patch data and content type
func (c *Client) PatchEthernetInterface(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateEthernetInterfaceStatus updates only the status of an existing EthernetInterface
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateEthernetInterfaceStatus(ctx context.Context, uid string, status v1.EthernetInterfaceStatus) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchEthernetInterfaceStatus patches only the status of an existing EthernetInterface
// Supports JSON Merge Patch by default. Use PatchEthernetInterfaceStatusWithType for other patch formats.
func (c *Client) PatchEthernetInterfaceStatus(ctx context.Context, uid string, patchData []byte) (*v1.EthernetInterface, error) {
	return c.PatchEthernetInterfaceStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchEthernetInterfaceStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchEthernetInterfaceStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.EthernetInterface, error) {
	var result v1.EthernetInterface
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteEthernetInterface deletes a EthernetInterface by UID
func (c *Client) DeleteEthernetInterface(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/ethernetinterfaces/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetGroups retrieves all groups
func (c *Client) GetGroups(ctx context.Context) ([]v1.Group, error) {
	var response []v1.Group
	if err := c.doRequest(ctx, "GET", "/groups", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetGroup retrieves a specific Group by UID
func (c *Client) GetGroup(ctx context.Context, uid string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateGroup creates a new Group
func (c *Client) CreateGroup(ctx context.Context, req CreateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	if err := c.doRequest(ctx, "POST", "/groups", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroup updates an existing Group
func (c *Client) UpdateGroup(ctx context.Context, uid string, req UpdateGroupRequest) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroup patches an existing Group spec with the specified patch data and content type
func (c *Client) PatchGroup(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateGroupStatus updates only the status of an existing Group
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateGroupStatus(ctx context.Context, uid string, status v1.GroupStatus) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchGroupStatus patches only the status of an existing Group
// Supports JSON Merge Patch by default. Use PatchGroupStatusWithType for other patch formats.
func (c *Client) PatchGroupStatus(ctx context.Context, uid string, patchData []byte) (*v1.Group, error) {
	return c.PatchGroupStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchGroupStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchGroupStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Group, error) {
	var result v1.Group
	endpoint := fmt.Sprintf("/groups/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteGroup deletes a Group by UID
func (c *Client) DeleteGroup(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/groups/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetHardwares retrieves all hardwares
func (c *Client) GetHardwares(ctx context.Context) ([]v1.Hardware, error) {
	var response []v1.Hardware
	if err := c.doRequest(ctx, "GET", "/hardwares", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetHardware retrieves a specific Hardware by UID
func (c *Client) GetHardware(ctx context.Context, uid string) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateHardware creates a new Hardware
func (c *Client) CreateHardware(ctx context.Context, req CreateHardwareRequest) (*v1.Hardware, error) {
	var result v1.Hardware
	if err := c.doRequest(ctx, "POST", "/hardwares", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateHardware updates an existing Hardware
func (c *Client) UpdateHardware(ctx context.Context, uid string, req UpdateHardwareRequest) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchHardware patches an existing Hardware spec with the specified patch data and content type
func (c *Client) PatchHardware(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateHardwareStatus updates only the status of an existing Hardware
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateHardwareStatus(ctx context.Context, uid string, status v1.HardwareStatus) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchHardwareStatus patches only the status of an existing Hardware
// Supports JSON Merge Patch by default. Use PatchHardwareStatusWithType for other patch formats.
func (c *Client) PatchHardwareStatus(ctx context.Context, uid string, patchData []byte) (*v1.Hardware, error) {
	return c.PatchHardwareStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchHardwareStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchHardwareStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.Hardware, error) {
	var result v1.Hardware
	endpoint := fmt.Sprintf("/hardwares/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteHardware deletes a Hardware by UID
func (c *Client) DeleteHardware(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/hardwares/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetRedfishEndpoints retrieves all redfishendpoints
func (c *Client) GetRedfishEndpoints(ctx context.Context) ([]v1.RedfishEndpoint, error) {
	var response []v1.RedfishEndpoint
	if err := c.doRequest(ctx, "GET", "/redfishendpoints", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetRedfishEndpoint retrieves a specific RedfishEndpoint by UID
func (c *Client) GetRedfishEndpoint(ctx context.Context, uid string) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateRedfishEndpoint creates a new RedfishEndpoint
func (c *Client) CreateRedfishEndpoint(ctx context.Context, req CreateRedfishEndpointRequest) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	if err := c.doRequest(ctx, "POST", "/redfishendpoints", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateRedfishEndpoint updates an existing RedfishEndpoint
func (c *Client) UpdateRedfishEndpoint(ctx context.Context, uid string, req UpdateRedfishEndpointRequest) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchRedfishEndpoint patches an existing RedfishEndpoint spec with the specified patch data and content type
func (c *Client) PatchRedfishEndpoint(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateRedfishEndpointStatus updates only the status of an existing RedfishEndpoint
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateRedfishEndpointStatus(ctx context.Context, uid string, status v1.RedfishEndpointStatus) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchRedfishEndpointStatus patches only the status of an existing RedfishEndpoint
// Supports JSON Merge Patch by default. Use PatchRedfishEndpointStatusWithType for other patch formats.
func (c *Client) PatchRedfishEndpointStatus(ctx context.Context, uid string, patchData []byte) (*v1.RedfishEndpoint, error) {
	return c.PatchRedfishEndpointStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchRedfishEndpointStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchRedfishEndpointStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.RedfishEndpoint, error) {
	var result v1.RedfishEndpoint
	endpoint := fmt.Sprintf("/redfishendpoints/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteRedfishEndpoint deletes a RedfishEndpoint by UID
func (c *Client) DeleteRedfishEndpoint(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/redfishendpoints/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetServiceEndpoints retrieves all serviceendpoints
func (c *Client) GetServiceEndpoints(ctx context.Context) ([]v1.ServiceEndpoint, error) {
	var response []v1.ServiceEndpoint
	if err := c.doRequest(ctx, "GET", "/serviceendpoints", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetServiceEndpoint retrieves a specific ServiceEndpoint by UID
func (c *Client) GetServiceEndpoint(ctx context.Context, uid string) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateServiceEndpoint creates a new ServiceEndpoint
func (c *Client) CreateServiceEndpoint(ctx context.Context, req CreateServiceEndpointRequest) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	if err := c.doRequest(ctx, "POST", "/serviceendpoints", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateServiceEndpoint updates an existing ServiceEndpoint
func (c *Client) UpdateServiceEndpoint(ctx context.Context, uid string, req UpdateServiceEndpointRequest) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchServiceEndpoint patches an existing ServiceEndpoint spec with the specified patch data and content type
func (c *Client) PatchServiceEndpoint(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateServiceEndpointStatus updates only the status of an existing ServiceEndpoint
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateServiceEndpointStatus(ctx context.Context, uid string, status v1.ServiceEndpointStatus) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchServiceEndpointStatus patches only the status of an existing ServiceEndpoint
// Supports JSON Merge Patch by default. Use PatchServiceEndpointStatusWithType for other patch formats.
func (c *Client) PatchServiceEndpointStatus(ctx context.Context, uid string, patchData []byte) (*v1.ServiceEndpoint, error) {
	return c.PatchServiceEndpointStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchServiceEndpointStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchServiceEndpointStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.ServiceEndpoint, error) {
	var result v1.ServiceEndpoint
	endpoint := fmt.Sprintf("/serviceendpoints/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteServiceEndpoint deletes a ServiceEndpoint by UID
func (c *Client) DeleteServiceEndpoint(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/serviceendpoints/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
